version: "3"

services:
  frontend:
    container_name: mrcide-packit-frontend
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest
    networks:
      - packit-local
    ports:
      - "3000:3000"
  backend:
    container_name: mrcide-packit-backend
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest
    depends_on:
      - outpack
    command:
      - docker exec packit-db wait-for-db
      - docker exec packit-db psql -U packituser -d packit -a -f /packit-schema/schema.sql
    networks:
      - packit-local
    ports:
      - "8080:8080"
  database:
    container_name: mrcide-packit-db
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest
    environment:
      - POSTGRES_USER=packituser
      - POSTGRES_PASSWORD=packitpassword
      - POSTGRES_DB=packit
    ports:
      - "5432:5432"
    networks:
      - packit-local

  outpack:
    container_name: outpack-server
    image: mrcide/outpack_server:main
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - packit-local
    volumes:
      - ./demos/orderly:/outpack

networks:
  packit-local:
