#!/usr/bin/env bash
set -ex

if [[ -v "GITHUB_SHA" ]]; then
    GIT_ID=${GITHUB_SHA:0:7}
else
    GIT_ID=$(git rev-parse --short=7 HEAD)
fi

if [[ -v "BRANCH_NAME" ]]; then
    GIT_BRANCH=${BRANCH_NAME}
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

REGISTRY=ghcr.io
ORG=mrc-ide
IMAGE_NAME=packit-db
TAG_SHA="${REGISTRY}/${ORG}/${IMAGE_NAME}:${GIT_ID}"
TAG_BRANCH="${REGISTRY}/${ORG}/${IMAGE_NAME}:${GIT_BRANCH}"
