#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
. $HERE/common

docker run --rm -d \
 --network=bridge \
 --name packit-db \
 -p 5432:5432 \
 "$TAG_BRANCH"

docker exec packit-db wait-for-db
$HERE/createSuperUser.sh