#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
. $HERE/common

docker run --rm -d \
 --network=bridge \
 --name packit-db \
 -p 5432:5432 \
 "$TAG_BRANCH"

# Need to give the database a little time to initialise before we can run the migration
docker exec packit-db wait-for-db
docker exec packit-db psql -U packituser -d packit -a -f /packit-schema/schema.sql
