#!/usr/bin/env bash
set -exu

# Export env vars needed for running test dependencies
export OUTPACK_SERVER_IMAGE=docker.io/mrcide/outpack_server:main
export ORDERLY_RUNNER_IMAGE=ghcr.io/mrc-ide/orderly.runner:mrc-6123

export RUNNER_CONTAINER_NAMESPACE=orderly.runner
export RUNNER_REDIS=$RUNNER_CONTAINER_NAMESPACE-redis
export RUNNER_GIT=$RUNNER_CONTAINER_NAMESPACE-git
export RUNNER_SERVER=$RUNNER_CONTAINER_NAMESPACE-server
export RUNNER_WORKER=$RUNNER_CONTAINER_NAMESPACE-worker

export ORDERLY_RUNNER_QUEUE_ID=orderly.runner.queue

export ORDERLY_LOGS_VOLUME=$RUNNER_CONTAINER_NAMESPACE-logs
