#!/usr/bin/env bash
set -exu

# Export env vars needed for running test dependencies
export ORG=mrcide
export OUTPACK_SERVER_TAG=$ORG/outpack_server:mrc-5089-default-branch

export CONTAINER_NAMESPACE=orderly.runner

export NETWORK=$CONTAINER_NAMESPACE-network
export REDIS=$CONTAINER_NAMESPACE-redis
export DEBUG=$CONTAINER_NAMESPACE-debug
export SERVER=$CONTAINER_NAMESPACE-server
export WORKER=$CONTAINER_NAMESPACE-worker

export ORDERLY_RUNNER_QUEUE_ID=orderly.runner.queue

export ORDERLY_VOLUME=$CONTAINER_NAMESPACE-orderly-root
export ORDERLY_REMOTE_VOLUME=$CONTAINER_NAMESPACE-orderly-root-remote

export ORDERLY_RUNNER_IMAGE=ghcr.io/mrc-ide/orderly.runner:mrc-5613-status-accept-list-ids

export CONTAINER_ORDERLY_ROOT_PATH=/orderly-root
export CONTAINER_ORDERLY_REMOTE_ROOT_PATH=/orderly-root-remote
