#!/usr/bin/env bash

set -eu

HERE=$(realpath "$(dirname $0)")
. "$HERE"/common

"$HERE"/../db/scripts/run 

docker exec packit-db wait-for-db

docker network create $RUNNER_NETWORK

docker run --rm -d \
       --net=$RUNNER_NETWORK \
       --name=$RUNNER_REDIS \
       -p 6379:6379 \
       redis

docker volume create $ORDERLY_VOLUME
docker volume create $ORDERLY_REMOTE_VOLUME

docker run -d --pull=missing \
       --name=$RUNNER_GIT_SETUP \
       --net=$RUNNER_NETWORK \
       -v $ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       -v $ORDERLY_REMOTE_VOLUME:$CONTAINER_ORDERLY_REMOTE_ROOT_PATH \
       --entrypoint="/bin/sh" \
       alpine/git \
       -c "sleep infinity"

docker cp $HERE/../demos/orderly/. $RUNNER_GIT_SETUP:$CONTAINER_ORDERLY_REMOTE_ROOT_PATH

docker exec $RUNNER_GIT_SETUP sh -c "mkdir /setup-repo"

docker cp $HERE/common $RUNNER_GIT_SETUP:/setup-repo/.
docker cp $HERE/docker-setup-git-repo $RUNNER_GIT_SETUP:/setup-repo/.

docker exec $RUNNER_GIT_SETUP /setup-repo/docker-setup-git-repo

docker run --pull=always --name outpack_server \
       --net=host \
       -v $ORDERLY_VOLUME:/outpack \
       -v $ORDERLY_REMOTE_VOLUME:$CONTAINER_ORDERLY_REMOTE_ROOT_PATH \
       -p 8000:8000 -d --rm \
       $OUTPACK_SERVER_TAG

docker run --rm -d --pull=always \
       --net=$RUNNER_NETWORK \
       --name=$RUNNER_SERVER \
       --entrypoint="/usr/local/bin/orderly.runner.server" \
       --env=ORDERLY_RUNNER_QUEUE_ID=$ORDERLY_RUNNER_QUEUE_ID \
       --env=REDIS_CONTAINER_NAME=$RUNNER_REDIS \
       -p 8001:8001 \
       -v $ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       $ORDERLY_RUNNER_IMAGE \
       $CONTAINER_ORDERLY_ROOT_PATH

docker run --rm -d --pull=always \
       --net=$RUNNER_NETWORK \
       --name=$RUNNER_WORKER \
       --entrypoint="/usr/local/bin/orderly.runner.worker" \
       --env=ORDERLY_RUNNER_QUEUE_ID=$ORDERLY_RUNNER_QUEUE_ID \
       --env=REDIS_CONTAINER_NAME=$RUNNER_REDIS \
       -v $ORDERLY_VOLUME:$CONTAINER_ORDERLY_ROOT_PATH \
       $ORDERLY_RUNNER_IMAGE \
       $CONTAINER_ORDERLY_ROOT_PATH
