#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

PACKAGE_ROOT=$(realpath $HERE/..)

$PACKAGE_ROOT/gradlew -p $PACKAGE_ROOT :app:bootDistTar

docker build -f $PACKAGE_ROOT/Dockerfile --tag $TAG_BRANCH $PACKAGE_ROOT

docker tag $TAG_BRANCH $TAG_SHA
