#!/usr/bin/env bash
set -e

HERE=$(dirname $0)
. $HERE/common

if [[ -n "$1" ]]; then
  echo auth method is $1
  $HERE/../../scripts/wait-notify \
    --docker-run -- \
    --rm \
    --network=host \
    --name packit-api \
    -e PACKIT_AUTH_METHOD=$1 \
    "$TAG_BRANCH"
else 
  $HERE/../../scripts/wait-notify \
    --docker-run -- \
    --network=host \
    --name packit-api \
    -e PACKIT_API_ROOT=http://localhost:8080 \
    "$TAG_BRANCH"
fi
