#!/usr/bin/env bash
wait_for()
{
    echo "waiting up to $TIMEOUT seconds for API"
    start_ts=$(date +%s)
    for i in $(seq $TIMEOUT); do

        result=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:8080/login)
        if [[ $result -eq 200 ]]; then
            end_ts=$(date +%s)
            echo "API available after $((end_ts - start_ts)) seconds"
            break
        fi
        sleep 1
        echo "...still waiting"
    done
    return $result
}

if [[ -v "BRANCH_NAME" ]]; then
    TAG=$BRANCH_NAME
else
    TAG=$(git symbolic-ref --short HEAD)
fi

# The variable expansion below is 60s by default, or the argument provided
# to this script
TIMEOUT="${1:-60}"
wait_for
RESULT=$?
if [[ $RESULT -ne 200 ]]; then
  echo "API did not become available in time"
  exit 1
fi
exit 0
