#!/usr/bin/env bash
set -e

# Unfortunately we need to build a Montagu-specific front end image which bakes in the front end and back end routes
# we expect to use for packit under the top level Montagu domain. This is because Montagu is not on nix so we use
# the constellation-based packit deployer which uses pre-built docker images rather than building the app at the point
# of deployment, as is done by the nix deployer for the other packit instances.

HERE=$(dirname $0)
. "$HERE"/common

MONTAGU_IMAGE_NAME=montagu-packit
MONTAGU_TAG_SHA="${REGISTRY}/${ORG}/${MONTAGU_IMAGE_NAME}:${GIT_ID}"
MONTAGU_TAG_BRANCH="${REGISTRY}/${ORG}/${MONTAGU_IMAGE_NAME}:${GIT_BRANCH}"

PACKAGE_ROOT=$(realpath $HERE/..)

docker build \
       -t "$MONTAGU_TAG_SHA" \
       -t "$MONTAGU_TAG_BRANCH" \
       --build-arg PUBLIC_URL=/packit \
       --build-arg VITE_PACKIT_API_URL=/packit/api \
       $PACKAGE_ROOT

docker push $MONTAGU_TAG_SHA
docker push $MONTAGU_TAG_BRANCH