#!/usr/bin/env bash
set -e
HERE=$(dirname $0)
. $HERE/common

PACKAGE_ROOT=$(realpath $HERE/..)

docker build \
       --build-arg PUBLIC_URL= \
       --build-arg VITE_PACKIT_API_URL=/api \
       -t "$TAG_SHA" \
       -t "$TAG_BRANCH" \
       $PACKAGE_ROOT
