#!/usr/bin/env bash
set -ex

GIT_ID=$(git rev-parse --short=7 HEAD)

if [[ -v "BRANCH_NAME" ]]; then
    GIT_BRANCH=${BRANCH_NAME}
else
    GIT_BRANCH=$(git symbolic-ref --short HEAD)
fi

REGISTRY=ghcr.io
ORG=mrc-ide
IMAGE_NAME=packit
TAG_SHA="${REGISTRY}/${ORG}/${IMAGE_NAME}:${GIT_ID}"
TAG_BRANCH="${REGISTRY}/${ORG}/${IMAGE_NAME}:${GIT_BRANCH}"
