name: backend-test
run-name: ${{ github.actor }} is testing packit backend features
on:
  workflow_run:
    workflows: [ "build-docker-db" ]
    types:
      - completed
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run dependencies
        run: ./scripts/run-dependencies
      - name: Set up Java JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "gradle"
      - name: Lint
        working-directory: api
        run: ./gradlew :app:detekt
      - name: Test backend
        working-directory: api
        run: ./gradlew :app:test --stacktrace --rerun
      - name: Build image
        working-directory: api
        run: ./gradlew :app:bootBuildImage --imageName=mrcide/packit:$BRANCH_NAME
