name: backend-test
run-name: ${{ github.actor }} is testing packit backend features
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "gradle"
      - name: test backend
        working-directory: api
        run: make test-backend
