name: backend-test
run-name: ${{ github.actor }} is testing packit backend features
on:
  workflow_run:
    workflows: ["build-docker-db"]
    types:
      - completed
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build DB
        uses: ./.github/actions/build-db
      - name: Run dependencies
        run: ./scripts/run-dependencies
        env:
          ORDERLY_RUNNER_LOGS_PATH: "${{ runner.temp }}/runner-logs"

      - name: Set up Java JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "gradle"
      - name: Test backend
        working-directory: api
        run: ./gradlew :app:test --stacktrace --rerun
        env:
          PACKIT_GITHUB_CLIENT_ID: ${{ secrets.PACKIT_GITHUB_CLIENT_ID }}
          PACKIT_GITHUB_CLIENT_SECRET: ${{ secrets.PACKIT_GITHUB_CLIENT_SECRET }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.PACKIT_GITHUB_ACCESS_TOKEN }}
      - name: Lint
        working-directory: api
        run: ./gradlew :app:detekt
      - name: Build image
        working-directory: api
        run: ./scripts/build-and-push
      - name: Smoke test
        working-directory: api
        run: ./scripts/run && ./scripts/smoke-test

      - name: Collect docker logs
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: "${{ runner.temp }}/docker-logs"

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: reports
          path: |
            api/app/build/reports/
            api/app/build/test-results/
            ${{ runner.temp }}/docker-logs
            ${{ runner.temp }}/runner-logs
