name: build-montagu-packit-front-end

on:
  push:
    branches:
      - "main" # Add feature branch here if you need a non-main image to deploy
  pull_request:
    branches:
      - "*"
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push montagu
        run: app/scripts/build-and-push-packit-for-montagu
