name: build-montagu-packit-front-end

on:
  push:
    branches:
      - "main" # Add feature branch here if you need a non-main image to deploy

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push montagu
        run: app/scripts/build-and-push-packit-for-montagu
