name: outpack-demo-build
run-name: ${{ github.actor }} is building an outpack demo
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build demo image
        working-directory: demos
        run: ./scripts/build-and-push
      - name: Smoke test
        working-directory: demos
        run: ./scripts/run test_volume
