# This checks that pull requests to main don't modify existing migrations.
# Doing so causes problems for deployment to existing instances.
name: check-migrations
on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check migrations haven't changed
        run: >
          git diff --exit-code --diff-filter=MD HEAD^ -- api/app/src/main/resources/db/migration
