name: test
run-name: ${{ github.actor }} is testing packit features
on: [push]
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout out repository
        uses: actions/checkout@v3

      - name: use Nodejs ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --prefix=app

      - name: Run build frontend
        run: npm run build --prefix=app

      - name: Run frontend test
        run: npm test --prefix=app --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
